#Disable Management Security to access actuator management endpoints in DEV
management:
  security:
    enabled: false
 
#Spring Caching and Redis Server Configuration    
spring:
  cache:
    type: redis  #The Type of Caching Provider ( Provide value as 'none' to disable caching )
  redis:
    sentinel:
      master: redis-cluster
      nodes: 127.0.0.1:16380,127.0.0.1:16381,127.0.0.1:16382
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

refresh:
  endpoint: http://localhost:8090/refresh
