#Disable Management Security to access actuator management endpoints in DEV
management:
  security:
    enabled: false
 
#Spring Caching and Redis Server Configuration    
spring:
  cache:
    type: redis  #The Type of Caching Provider ( Provide value as 'none' to disable caching )

redisSentinelMaster: redis-cluster    
redisSentinelHost1: 127.0.0.1
redisSentinelPort1: 16380
redisSentinelHost2: 127.0.0.1
redisSentinelPort2: 16381
redisSentinelHost3: 127.0.0.1
redisSentinelPort3: 16382





    
endpoints:
  restart:
    enabled: true

