#Disable Management Security to access actuator management endpoints in DEV
management:
  security:
    enabled: false
 


server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/side-projects/cache-demos/config-repo

          
  profiles:
    active:
    - native
    